Repository scunning-sps/spring21-sps-26, pull requests merged in 2021-04, with the labels that each got.

#8 Dario datastore for guides
  pom.xml
  src/main/java/com/google/sps/data/Guide.java
  src/main/java/com/google/sps/servlets/GuidesServlet.java
  src/main/java/com/google/sps/storage/DatastoreGuides.java
Labels: enhancement

#9 Adds documentation to use datastore emulator.
  README.md
Labels: documentation

#11 Post guide API enhancements
  README.md
  src/main/java/com/google/sps/servlets/GuidesServlet.java
  src/main/webapp/testAPI.js
Labels: documentation, enhancement

#12 Changes the datastore emulator guide to a walkthrough
  README.md
  datastore-emulator.md
Labels: documentation

#10 Get individual guide endpoint for the API
  README.md
  src/main/java/com/google/sps/data/Error.java
  src/main/java/com/google/sps/servlets/SpecificGuideServlet.java
  src/main/java/com/google/sps/storage/DatastoreGuides.java
Labels: documentation, enhancement

#13 Test guides enhancements
  src/main/java/com/google/sps/storage/DatastoreGuides.java
  src/main/webapp/testAPI.js
Labels: enhancement

#14 Add nav-bar to home page
  src/main/webapp/index.html
  src/main/webapp/style.css
Labels: enhancement

#15 Navigation for guides and guide cards
  src/main/webapp/index.html
  src/main/webapp/script.js
  src/main/webapp/style.css
Labels: enhancement

#17 Category for guides on the API
  README.md
  src/main/java/com/google/sps/data/Guide.java
  src/main/java/com/google/sps/servlets/GuidesServlet.java
  src/main/java/com/google/sps/storage/DatastoreGuides.java
  src/main/webapp/testAPI.js
Labels: enhancement

#16 Fetches guides from datastore to populate the home page
  src/main/webapp/index.html
  src/main/webapp/script.js
  src/main/webapp/style.css
Labels: enhancement

#23 Dario delete guide
  src/main/java/com/google/sps/servlets/GuidesServlet.java
  src/main/java/com/google/sps/servlets/SpecificGuideServlet.java
  src/main/java/com/google/sps/storage/DatastoreGuides.java
  src/main/webapp/form.html
  src/main/webapp/script.js
  src/main/webapp/testAPI.js
Labels: enhancement
